server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/425
    username: root
    password: wanghongyu
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
